#!/usr/bin/env bash
#Tell the story of passwd

while IFS=: read -r USERNAME GROUP_ID HOME SHELL USER_ID PASSWORD; do
	echo "The user $USERNAME is part of the $PASSWORD gang, lives in $USER_ID and rides $GROUP_ID. $USER_ID's place is protected by the passcode $HOME, more info about the user here: $SHELL"
done < /etc/passwd

