#!/usr/bin/env bash
#Tell the story of passwd
#while IFS=: read -r USERNAME GROUP_ID HOME SHELL USER_ID PASSWORD; do
#	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME and rides $SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID"
#done < /etc/passwd

while IFS=: read -r USERNAME GROUP_ID HOME SHELL USER_ID PASSWORD; do
echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME and rides $SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID"
done < /etc/passwd
