#!/usr/bin/env bash
# using while, if and elif
i=1
while [[ $i -le 10 ]]
     do
     	echo "Best School"
	
	((i++))
	if [[ $i -eq 4 ]]; then
	echo "bad luck"
	elif [[ $i -eq 8 ]]; then
	echo "good luck"
fi
done	
