#!/usr/bin/env bash
# superstitious numbers
i=1
while [ $i -le 20 ]; do 
case $i in
	4) echo "4\nbad luck from China"
		;;
	9) echo "9\nbad luck from Japan"
		;;
	17) echo "17\nbad luck from Italy"
		;;	
	*) echo $i

	esac 
	i=$((i+1))
done	
