#!/usr/bin/env bash
# Clock
hour=0
minute=1
echo "Hour: $hour"

while [ $hour -le 11 ]; do
       echo $minute
       ((minute++))
       if [ $minute -gt 59 ]; then 
	       hour=$((hour + 1))
	       echo "Hour: $hour"
	       minute=1
	       
       fi
done

#echo $minute
#((minute++))
while [ $minute -le 59 ]; do
	echo $minute 
if [ $minute -gt 59 ]; then
	break
fi
minute=$((minute+1))
done

