#!/usr/bin/env bash
# Clock
hour=0
minute=1
echo "Hour: $hour"

while [ $hour -le 11 ]; do
       echo $minute
       ((minute++))
       if [ $minute -gt 59 ]; then 
	       hour=$((hour + 1))
	       echo "Hour: $hour"
	       minute=1
	       

       fi
      
done
