#!/usr/bin/env bash
#To file, or not to file
school=$(ln -s school)
if [ -f "$school" ]; then
	echo "school file exists"
	if [ -s "$school" ]; then
		echo "school file is not empty"

			if [ -r "$school" ]; then
			echo "school is a regular file"
			else
			echo ""
			fi

		else
		echo "school file is empty"
			if [ -r "$school" ]; then
                        echo "school is a regular file"
                	fi

		fi
else 
	echo "school file does not exist"
fi
