#!/usr/bin/env bash
#To file, or not to file
school=$(basename school)
if [ -f "$school" ]; then
	echo "school file exists"
	if [ -s "$school" ]; then
		echo "school file is not empty"

		if [ -r "$school" ]; then
			echo "school is a regular file"
		fi

	else
		echo "school file is empty"
	fi
else 
	echo "school file does not exist"
fi
