#!/usr/bin/env bash
#Process and PID file

function fileDel() {
rm /var/run/myscript.pid
exit
}

trap 'echo "Y U no love me?!' SIGINT
trap 'echo "I hate the kill command"; fileDel' SIGTERM
#trap 'rm /var/run/myscript.pid; exit' SIGQUIT SIGTERM

pid=$(pgrep -f myscript.sh)
echo "$pid" > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
done

