#!/usr/bin/env bash
#Highlander
while true; do
	echo "To infinity and beyond"
	sleep 2
done

trap 'echo "I am invincible!!!"' kill

pid=$(pgrep -f 7-highlander)
kill "$pid"
wait "$pid"
echo "The 7-highlander process has been terminated."
