#!/usr/bin/env bash
#Highlander
trap 'echo "I am invincible!!!"' SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done


pid=$(pgrep -f 7-highlander)
kill "$pid"
wait "$pid"
echo "The 7-highlander process has been terminated."
